-- MySQL Script generated by MySQL Workbench
-- Tue 02 Jul 2019 04:48:13 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ChainRaceDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ChainRaceDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ChainRaceDB` DEFAULT CHARACTER SET utf8 ;
USE `ChainRaceDB` ;

-- -----------------------------------------------------
-- Table `ChainRaceDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(128) NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `email` VARCHAR(32) NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` TEXT NOT NULL,
  `stat_end_time` FLOAT NOT NULL COMMENT 'AWS stat',
  `stat_percentage` FLOAT NOT NULL COMMENT 'AWS stats ',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`vehicule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(128) NOT NULL,
  `pac` VARCHAR(128) NOT NULL COMMENT 'Password entered in the Raspberry chip so the car can communicate with the server endpoint.',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`user_has_vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`user_has_vehicule` (
  `user_id` INT NOT NULL,
  `vehicule_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `vehicule_id`),
  INDEX `fk_user_has_vehicule_vehicule1_idx` (`vehicule_id` ASC),
  INDEX `fk_user_has_vehicule_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_vehicule_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ChainRaceDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_vehicule_vehicule1`
    FOREIGN KEY (`vehicule_id`)
    REFERENCES `ChainRaceDB`.`vehicule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`model_update`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`model_update` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(2) NOT NULL COMMENT 'AW = awaiting\nOK = updated\nKO = failed',
  `user_id` INT NOT NULL,
  `vehicule_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `model_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `vehicule_id`, `model_id`),
  INDEX `fk_model_update_user_has_vehicule1_idx` (`user_id` ASC, `vehicule_id` ASC),
  INDEX `fk_model_update_model1_idx` (`model_id` ASC),
  CONSTRAINT `fk_model_update_user_has_vehicule1`
    FOREIGN KEY (`user_id` , `vehicule_id`)
    REFERENCES `ChainRaceDB`.`user_has_vehicule` (`user_id` , `vehicule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_model_update_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `ChainRaceDB`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`model_add`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`model_add` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `model_id`),
  INDEX `fk_model_add_user1_idx` (`user_id` ASC),
  INDEX `fk_model_add_model1_idx` (`model_id` ASC),
  CONSTRAINT `fk_model_add_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ChainRaceDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_model_add_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `ChainRaceDB`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(128) NOT NULL,
  `name` VARCHAR(128) NULL,
  `starts_at` TIMESTAMP NOT NULL,
  `ends_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`race` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contest_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `vehicule_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `contest_id`, `user_id`, `vehicule_id`),
  INDEX `fk_race_contest1_idx` (`contest_id` ASC),
  INDEX `fk_race_user_has_vehicule1_idx` (`user_id` ASC, `vehicule_id` ASC),
  CONSTRAINT `fk_race_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `ChainRaceDB`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_race_user_has_vehicule1`
    FOREIGN KEY (`user_id` , `vehicule_id`)
    REFERENCES `ChainRaceDB`.`user_has_vehicule` (`user_id` , `vehicule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`user_has_contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`user_has_contest` (
  `user_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `type` VARCHAR(2) NOT NULL COMMENT 'JO = joined\nCR = created',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `contest_id`),
  INDEX `fk_user_has_contest_contest1_idx` (`contest_id` ASC),
  INDEX `fk_user_has_contest_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_contest_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ChainRaceDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_contest_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `ChainRaceDB`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`stats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'started_at, ended_at, stopped_at',
  `value` INT NOT NULL,
  `race_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stats_race1_idx` (`race_id` ASC),
  CONSTRAINT `fk_stats_race1`
    FOREIGN KEY (`race_id`)
    REFERENCES `ChainRaceDB`.`race` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `public_key` TEXT NOT NULL,
  `address` TEXT NOT NULL,
  `passphrase` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChainRaceDB`.`user_has_wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChainRaceDB`.`user_has_wallet` (
  `user_id` INT NOT NULL,
  `wallet_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `wallet_id`),
  INDEX `fk_user_has_wallet_wallet1_idx` (`wallet_id` ASC),
  INDEX `fk_user_has_wallet_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_wallet_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ChainRaceDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_wallet_wallet1`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `ChainRaceDB`.`wallet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
